### ISSUE TITLE
Error when changing color

### ISSUE THREAD

**Issue by AlexBlck** [andfanilo/streamlit-component-template-vue#18]
[duplicate of [this](https://github.com/andfanilo/streamlit-drawable-canvas-demo/issues/2#issue-923793972)]

In the [basic example](https://share.streamlit.io/andfanilo/streamlit-drawable-canvas-demo/master/app.py)

After clicking out of color picker, this happens:

![image](https://user-images.githubusercontent.com/39992844/122384866-05727b00-cf64-11eb-8ca1-5a3205cf6f8e.png)

`SecurityError: Blocked a frame with origin "https://apps.streamlitusercontent.com" from accessing a cross-origin frame.
`
```at t.value (https://apps.streamlitusercontent.com/andfanilo/streamlit-drawable-canvas-demo/master/app.py/+/static/js/5.d3fb5f21.chunk.js:2:3546415)
at t.value (https://apps.streamlitusercontent.com/andfanilo/streamlit-drawable-canvas-demo/master/app.py/+/static/js/5.d3fb5f21.chunk.js:2:3546529)
at t.value (https://apps.streamlitusercontent.com/andfanilo/streamlit-drawable-canvas-demo/master/app.py/+/static/js/5.d3fb5f21.chunk.js:2:3546304)
at Al (https://apps.streamlitusercontent.com/andfanilo/streamlit-drawable-canvas-demo/master/app.py/+/static/js/5.d3fb5f21.chunk.js:2:2491558)
at Ml (https://apps.streamlitusercontent.com/andfanilo/streamlit-drawable-canvas-demo/master/app.py/+/static/js/5.d3fb5f21.chunk.js:2:2493361)
at Cs (https://apps.streamlitusercontent.com/andfanilo/streamlit-drawable-canvas-demo/master/app.py/+/static/js/5.d3fb5f21.chunk.js:2:2505454)
at t.unstable_runWithPriority (https://apps.streamlitusercontent.com/andfanilo/streamlit-drawable-canvas-demo/master/app.py/+/static/js/5.d3fb5f21.chunk.js:2:2526071)
at jn (https://apps.streamlitusercontent.com/andfanilo/streamlit-drawable-canvas-demo/master/app.py/+/static/js/5.d3fb5f21.chunk.js:2:2448429)
at xs (https://apps.streamlitusercontent.com/andfanilo/streamlit-drawable-canvas-demo/master/app.py/+/static/js/5.d3fb5f21.chunk.js:2:2503412)
at As (https://apps.streamlitusercontent.com/andfanilo/streamlit-drawable-canvas-demo/master/app.py/+/static/js/5.d3fb5f21.chunk.js:2:2499498)
```

Also happens in other apps, eg [here](https://share.streamlit.io/alexblck/compsketch/share/src/streamlit_app.py)

**Comment by andfanilo** [comment]
Yeah unfortunately :( https://github.com/streamlit/streamlit/issues/2689 you could add a +1 to this issue.

Hope it gets fixed soon. I'll close this one as a duplicate and we can follow the one on my other repo.

Have a good day,
Fanilo
